### ISSUE TITLE
Create task with line text instead of file name

### ISSUE THREAD

**Issue by royxue** [viduycheung/ticktick-obsidian#10]
Hey

Thanks for developing this plugin, it's awesome.

I found that now the new task can only be created from file title.
I was thinking maybe it would be nice to add a new feature that can create task with certain line of text in file.(link can still be file link)

**Comment by viduycheung** [comment]
You can select the desired text and then run the command; the selected text will become the task title

![CleanShot 2024-01-16 at 11  52 58@2x](https://github.com/viduycheung/ticktick-obsidian/assets/53415256/2828007e-e06d-4eb6-8c7f-fc409d0917f4)

**Comment by royxue** [comment]
@viduycheung nice, didnt notice this before, thanks for explanation.
gonnna close this ;)
