### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by denizido** [viduycheung/ticktick-obsidian#2]
Hello, first of all, congratulations on this plugin; I've been waiting for a ticktick integration for a long time.

I wonder if there are new features planned, like adding note content to task

Or even maybe task and note syncronizatioin.

Thank you in advance, and once again, great job.

**Comment by viduycheung** [comment]
Hello, we currently do not have any new feature development plans. However, if you have any ideas or suggestions, feel free to share them with us. We will consider implementing and releasing them.

**Comment by 39mm** [comment]
Hi, I think that it would be great if the plugin would have capability to review and close tasks.

For example, this Todoist plugin has very good integration, with option to filter, and sort tasks:

https://github.com/jamiebrynes7/obsidian-todoist-plugin

Thank you for your time and effort.

**Comment by viduycheung** [comment]
Unfortunately, this feature cannot be implemented due to limitations in the TickTick OpenAPI. You can find more information here: https://developer.ticktick.com/api#/openapi?id=api-reference.

**Comment by arturoscm** [comment]
@viduycheung 

Hi. I love the plugin. One question: I installed it and I have the token that Ticktick gives me, I copy it but I can't find where to "paste" it in obsidian:

Image: [im](https://monosnap.com/file/upEwHQJgO6hAFTsCIxgQT7yiCT8YuD)

Could you tell me how and where to paste the token?

Thank you.

**Comment by arturoscm** [comment]
@viduycheung

Hola. Me encanta el complemento. Una pregunta: lo instalé y tengo el token que me da Ticktick, lo copio pero no encuentro donde "pegarlo" en obsidiana:

Imagen: [image obsidian](https://monosnap.com/file/upEwHQJgO6hAFTsCIxgQT7yiCT8YuD)

¿Podrías decirme cómo y dónde pegar el token?

Gracias.

**Comment by arturoscm** [comment]
@viduycheung 

Hi. I love the plugin. One question: I installed it and I have the token that Ticktick gives me, I copy it but I can't find where to "paste" it in obsidian:

Image: [image obsidian](https://monosnap.com/file/upEwHQJgO6hAFTsCIxgQT7yiCT8YuD)

Could you tell me how and where to paste the token?

Thank you.
