### ISSUE TITLE
links to obsidian from ticktick how do they work?

### ISSUE THREAD

**Issue by santiyounger** [viduycheung/ticktick-obsidian#3]
Hey thanks for the plugin!! Not sure if it's currently broken, but creating a new ticktick task from Obsidian creates a title that's not clickable on ticktcik

## in obsidian
![image](https://github.com/viduycheung/ticktick-obsidian/assets/51902730/42c045b6-b381-40b7-8efa-d1eab45e45c5)

## in ticktick
![image](https://github.com/viduycheung/ticktick-obsidian/assets/51902730/f217e198-869b-4907-a2a4-2aa1bd4e3c28)

In the README I got the impression I could see my ticktick tasks in Obsidian, if not I was hoping there's a way to link quickly to sections of my obsidian from ticktick.

Perphaps I just found a bug, thanks for your help

**Comment by viduycheung** [comment]
Fixed in 1.0.2, please update your plugin to 1.0.2.

**Comment by santiyounger** [comment]
awesome thank you
