### ISSUE TITLE
Dont support Chinese account

### ISSUE THREAD

**Issue by how2051** [viduycheung/ticktick-obsidian#5]
Could this plugin support Chinese account of ticktick ?
(FYI, the Chinese version of ticktick is called dida, and I use my dida account trying to login and failed.)

(but it seems that they use the same API, so it might be no difference ?)

How can I get my token if I cant login using the website your plugin offer in `here`

**Comment by viduycheung** [comment]
I submitted another plugin that supports the DIDA account. You can download it after this PR is merged. https://github.com/obsidianmd/obsidian-releases/pull/2644
