### ISSUE TITLE
Activation of the Ticktick Token in Obsidian (Windows)

### ISSUE THREAD

**Issue by arturoscm** [viduycheung/ticktick-obsidian#6]
@viduycheung 

Hi. I love the plugin. One question: I installed it and I have the token that Ticktick gives me, I copy it but I can't find where to "paste" it in obsidian:

Video: [Problem details](https://monosnap.com/file/dsRlbkhNrpPBVSTYf9I7Ss5qgqL1md)

Could you tell me how and where to paste the token?

Thank you.

**Comment by viduycheung** [comment]
You need to paste the token into this input filed.
![CleanShot 2023-11-13 at 10  32 32@2x](https://github.com/viduycheung/ticktick-obsidian/assets/53415256/66919cd3-699c-48fd-b60a-aa9585640f54)

**Comment by arturoscm** [comment]
Ok. It worked. Thanks.
