### ISSUE TITLE
Support dida

### ISSUE THREAD

**Issue by quanru** [viduycheung/ticktick-obsidian#8]
ticktick has a china version which official site is https://dida365.com/, and its base url is https://api.dida365.com/

https://developer.dida365.com/docs#/openapi

**Comment by viduycheung** [comment]
You can fork this repository and build it yourself. Obsidian is not allowed two extensions with similar functions based on different service providers. 
https://github.com/viduycheung/dida-obsidian

**Comment by quanru** [comment]
> You can fork this repository and build it yourself. Obsidian is not allowed two extensions with similar functions based on different service providers. https://github.com/viduycheung/dida-obsidian

Can you support switching between Dida and Ticktick in the plugin settingtab?

**Comment by viduycheung** [comment]
No, it will confuse users who are not familiar with DIDA.
